---
    apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: foundryvtt
      namespace: foundryvtt
      annotations:
        kubernetes.io/ingress.class: traefik
    spec:
      rules:
        - host: your.domain
          http:
            paths:
              - backend:
                  serviceName: foundryvtt-web
                  servicePort: web
      tls:
        - secretName: foundryvtt-web-tls-cert