---
    apiVersion: kustomize.config.k8s.io/v1beta1
    kind: Kustomization
    namespace: foundryvtt
    
    commonLabels:
      app: foundryvtt
    
    resources:
      - 00-namespace.yml
      - 01-persisted-volume-claim.yml
      - 02-deployment.yml
      - 03-web-service.yml
      - 04-ingress.yml
    
    secretGenerator:
      - name: foundryvtt-env
        # env is a path to a file to read lines of key=val
        # you can only specify one env file per secret.
        env: secrets/env.txt
        type: Opaque
      - name: foundryvtt-web-tls-cert
        files:
          - secrets/tls.crt
          - secrets/tls.key
        type: "kubernetes.io/tls"